# Copyright 2024 The NativeLink Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is @generated by lre-cc.

"""Module extension to register different lre-cc tool repositories."""

load("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")

def _lre_cc_impl(_mctx):
    new_local_repository(
        name = "lre-cc-aarch64-darwin",
        build_file = "@local-remote-execution//cc:aarch64-darwin.BUILD.bazel",
        path = "/nix/store/5f8g1gyj7cssly90dsy2f0jimgwyjr5r-clang-wrapper-19.1.7",
    )
    new_local_repository(
        name = "lre-cc-clang-aarch64-darwin",
        build_file = "@local-remote-execution//cc:aarch64-darwin-clang.BUILD.bazel",
        path = "/nix/store/syiggy82xdfg8rh5092xg18cqs4pcli2-clang-19.1.7",
    )
    new_local_repository(
        name = "lre-cc-libclang-aarch64-darwin",
        build_file = "@local-remote-execution//cc:aarch64-darwin-libclang.BUILD.bazel",
        path = "/nix/store/cx5gh7gwhv06j4llivklbkfxyfgnk3sp-clang-19.1.7-lib",
    )
    new_local_repository(
        name = "lre-cc-aarch64-linux",
        build_file = "@local-remote-execution//cc:aarch64-linux.BUILD.bazel",
        path = "/nix/store/pxmkd8rp0yqf1mvfacgv1wbp7r95gckx-clang-wrapper-19.1.7",
    )
    new_local_repository(
        name = "lre-cc-clang-aarch64-linux",
        build_file = "@local-remote-execution//cc:aarch64-linux-clang.BUILD.bazel",
        path = "/nix/store/xl8gk5s20zx7whvcd8bsxkkxqmqjhllc-clang-19.1.7",
    )
    new_local_repository(
        name = "lre-cc-libclang-aarch64-linux",
        build_file = "@local-remote-execution//cc:aarch64-linux-libclang.BUILD.bazel",
        path = "/nix/store/jxj66f46vvhiqy1f0i0p12lalza64mgy-clang-19.1.7-lib",
    )
    new_local_repository(
        name = "lre-cc-x86_64-darwin",
        build_file = "@local-remote-execution//cc:x86_64-darwin.BUILD.bazel",
        path = "/nix/store/5qxvs86l0a4ifzs3a9w3p75vh2nkd6ls-clang-wrapper-19.1.7",
    )
    new_local_repository(
        name = "lre-cc-clang-x86_64-darwin",
        build_file = "@local-remote-execution//cc:x86_64-darwin-clang.BUILD.bazel",
        path = "/nix/store/91x93647g26jxqjnxwbrc73wx2ljakzl-clang-19.1.7",
    )
    new_local_repository(
        name = "lre-cc-libclang-x86_64-darwin",
        build_file = "@local-remote-execution//cc:x86_64-darwin-libclang.BUILD.bazel",
        path = "/nix/store/rzz86zb6h7zwjcl8nd221nw2d9hi03z2-clang-19.1.7-lib",
    )
    new_local_repository(
        name = "lre-cc-x86_64-linux",
        build_file = "@local-remote-execution//cc:x86_64-linux.BUILD.bazel",
        path = "/nix/store/pcknhp59jx07gclcx5pgpckk75zz0q2p-clang-wrapper-19.1.7",
    )
    new_local_repository(
        name = "lre-cc-clang-x86_64-linux",
        build_file = "@local-remote-execution//cc:x86_64-linux-clang.BUILD.bazel",
        path = "/nix/store/2kwyhb62gfj00403q9p8fbj0gag96bzv-clang-19.1.7",
    )
    new_local_repository(
        name = "lre-cc-libclang-x86_64-linux",
        build_file = "@local-remote-execution//cc:x86_64-linux-libclang.BUILD.bazel",
        path = "/nix/store/65rh16mh99fln30ba6bhg37d0gygc3ch-clang-19.1.7-lib",
    )

lre_cc = module_extension(implementation = _lre_cc_impl)
